scragg0x/realms-wiki

README.md

I just played with this and nginx is keeping the **/static/** in the requesting url and then attempting to find a folder on the file system that looks like **/full/path/to/realms/static/static/...**
This should fix that.

nginx static content location root fixed

---

README.md
realms/config/__init__.py
realms/modules/search/models.py

This makes the fields searched by Elasticsearch configurable, allowing searching of article text as well as page titles. Default behaviour remains the same. Also proposed an edit to docs to include the new config option.
- Added config item `ELASTICSEARCH_FIELDS`
- Use the item [in the elasticsearch model](https://github.com/darkindex/realms-wiki/blob/elasticsearch-fields/realms/modules/search/models.py#L17) - is this the correct way to pass this value in?
- Updated README

Make Elasticsearch searched fields configurable

---

bower.json

This version includes a fix for a DataTables bug that can cause JS errors.
Possibly only affects certain jQuery versions but seems reproducible with 1.11.3
Bug report: https://github.com/DataTables/DataTables/issues/546
Commit: https://github.com/DataTables/DataTablesSrc/commit/485b259e5c

Update DataTables dependency to 1.10.7

---

realms/commands.py

Sorry.
There was a subtle bug in the parameter handling
The parameter names must not be converted to upper case before calling
`context.invoke`, because that works with the lowercase names.
Before this bugfix,, we had kw like this in the various `setup_*` functions: `{'DB_URI': 'sqlite:////tmp/wiki.db', 'db_uri': 'sqlite:////real/path.db'}` and whichever won was pretty much random (dict sort order)

Fix subtle bug in new click parameter handling

---

realms/modules/search/commands.py

Noticed sometimes `wiki.get_page()` might return None, which halts the entire index process. (Seems to be the case if I have some non-markdown files or something)

Make rebuild_index() more robust

---

realms/modules/search/hooks.py
realms/modules/search/models.py
realms/modules/wiki/models.py
realms/modules/wiki/views.py
realms/static/js/editor.js
realms/templates/wiki/edit.html

Fix bug where renaming a page doesn't delete the old page. The editor code (`edit.html` and `editor.js`) needs to know what the existing page name is to do this (right now it only look at the new page name, stored in `$('#page-name')`
Now renaming a page will produce the correct values for `old_name` and `new_name ` in https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/wiki/models.py#L106, so that the `old_name` will be removed.
See my comment in https://github.com/scragg0x/realms-wiki/issues/61
Let me know if there are other preferred conventions (e.g. `PAGE_NAME`)
EDIT: also added functionality to delete search indices for ES and Whoosh (I'm not familiar with Whoosh but tried to piece if together)
EDIT2 (9/29): also found a bug where rename_page() would get called …

Fix bug with rename page to also delete old page

---

realms/modules/search/commands.py

Should fix #88. The full path of the pages was not being sent to the search provider when rebuild_index command was run.

Fix rebuild_index to use full path of page when indexing.

---

realms/modules/wiki/views.py
realms/templates/wiki/index.html

This is just a start, I also want to support showing directories folded up with links to the index of them. I'm not sure if this should be an option, or if we should just always do it. If it's an option, should it be for the whole realms instance, or a parameter to the url, or both?
@scragg0x Thoughts?

Support getting indexs of subdirs

---

realms/modules/wiki/views.py
realms/templates/wiki/index.html

This could probably stand to be tweaked and cleaned up a bit still, but it seems to be working. There are a few changes here:
- Subdirectories will now be listed in the index rather than all their files
- The title of the index page showing the current path works like breadcrumbs to go to higher level paths
- Fixed the column headers for mtime and ctime being reversed
I'll clean it up if you have any comments, I'm sleepy now, and figured I'd put it up for review.
Would be pretty easy to add an option to enable flat view, it's just a matter of returning `items` or `_tree_view(items)`

Implements a tree view index

---

realms/templates/wiki/index.html

Also changes the initial sorting to show dirs first then pages.
I don't really know what I'm doing with html/css, so the following things should maybe be improved:
- I'm using text in the icon column with a hidden style so sorting works, I'm not sure if there is a better way.
- I'm also setting the width of that column to 1px to make datatables shrink it as much as possible, not sure if there is a better way for that.

Add an icon and sort column for pages/dirs in the index

---

realms/modules/wiki/models.py
realms/modules/wiki/views.py
realms/static/css/style.css
realms/templates/layout.html
realms/templates/wiki/history.html

This adds author_email to the return of Wiki.get_history, which is used by the history wiki view to generate a gravatar url.
I've also switched the gravatar styling from the menu a bit to be easier to use with gravatar icons in other places, though not sure if I did it the best way.

Add gravatar icons to history

---

realms/config/__init__.py

I was trying to add a custom module in for some site specific customization, and noticed MODULES could not be specified from the config file.

Allow all config options to be specified in realms-wiki.json

---

docker/realms-wiki.sh

There's a bug in realms-wiki.sh which prevents the docker image from starting correctly if REALMS_WIKI_CONFIG variable contains spaces (e.g. site title could contains spaces).

Properly escape REALMS_WIKI_CONFIG variable

---

realms/__init__.py

With this small patch datetimes are made customizable either in the individual templates or as a global default set by the `DATETIME_FORMAT` variable.
If the `datetime` filter is given an argument in a template, that value will be used in formatting the string. E.g.:
```html
<td>{{ h.time|datetime('%d-%b-%Y %H:%M') }}</td>
```
could result in
```html
<td>23-Jan-2016 12:34</td>
```
If no arguments are given, `realms-wiki` will attempt to use the formatting template from the `DATETIME_FORMAT` variable, e.g.:
```json
{
"ALLOW_ANON": false,
"BASE_URL": "http://localhost",
"CACHE_TYPE": "simple",
"DATETIME_FORMAT": "%F %T",
"DB_URI": "sqlite:////tmp/wiki.db",
"PORT": 5000,
"REGISTRATION_ENABLED": true,
"SEARCH_TYPE": "simple",
"SECRET_KEY": "ey2hYoYyg2CeA22Q9ZX8Jcn8",
"SITE_TITLE": "Realms", …
```

Make datetimes customizable

---

README.md

The current link is a 404, and goes to google's style guide.
Google's style guide recommends pylint, which runs with 77 errors, 50
warn, 35 refactor, and 336 convention messages.
By pep8, there are 122 messages, mostly line length and imports not
being at the top of the file.
So I've made the assumption this is meant to be based on pep8 to that.

Update README style guide link

---

realms/modules/wiki/views.py

There aren't any interface elements to open flat mode, but I thought since it's so simple to maintain support it might be useful still.

Allow a flat view of index with the 'flat' query parameter

---

realms/lib/test.py
realms/modules/search/commands.py
realms/modules/search/models.py
realms/modules/wiki/models.py
realms/modules/wiki/tests.py
realms/modules/wiki/views.py

I was looking in to #145, and discovered that wiki.get_history was very slow when the repo had a lot of commits, even when limited to the first entry, like wiki.get_page was using to fill the page['info'] dict. I also noticed that most usages of get_page didn't even use the provided info dict.
This PR refactors wiki.get_page() to return a new class, `WikiPage`, which has `data`, `info`, and `partials` properties, lazily loaded when accessed. This means the expensive `info` property never needs to be loaded when browsing the site normally.
The WikiPage class is also the only thing that touches the cache now, and the `data` and `info` property are cached separately.
I'm developing on Windows at the moment, and haven't gotten my testing environment set up yet, so there may be a couple tweaks …

Create WikiPage class to encapsulate wiki page functions

---

realms/modules/wiki/models.py

I may make a PR to gittle to see if they want to do it there, but wanted to fix #152 quickly. This also adds a commit method to Wiki model, which I also plan to use for an upcoming hook to auto sync the repo to a remote.

Ensure git repo remains valid with unicode committer names. fix #152

---

realms/__init__.py
realms/commands.py
realms/modules/auth/local/commands.py
realms/modules/search/commands.py

It seems commands registered by submodules got a little bit borked by bd41eaac4ef9b8e154558cfa7993f0d46acdb434 Instead of modules creating click groups that later got registered, they started calling the AppGroup().group method, which already registered them under the 'cli' subcommand name, and each successive module cli command would overwrite the last.
I wasn't sure the way we wanted to solve it, but I figured we didn't want the modules just auto-registering themselves on import (do we?) I made a `realms.cli_group` decorator that modules can use to declare create their command group (like the `click.group` function, but sets `cls=AppGroup`,) and then the application registers the command during discovery phase. Since the context is now being opened externally, I also stripped that bit …

Fix CLI registration for module command groups. fix #103

---

realms/modules/search/commands.py
realms/modules/wiki/models.py
realms/modules/wiki/tests.py
realms/modules/wiki/views.py
realms/templates/errors/404.html
realms/templates/wiki/history.html

This addresses most of the concerns from #149. It makes a `WikiPage.history` property, which is an iterator rather than a list. This means thing using the property, like the history view, can use itertools.islice or similar methods to only load up to a certain point. I've also added `WikiPage.history_cache`, which returns the number of cached items in history, as well as whether the cache is complete. Not super nice, but that info is needed to get good paging functionality in the history view. I've also removed the info property, with reasoning from #148. I didn't delete the usages of it from search indexer or edit page view, which I think should probably also go.
I redid the history view to use datatables, which gets the data via ajax calls. When the history hasn't been fully cached, the …

History optimization/improvement fix #149

---

realms/lib/hook.py

Just causes an error if you try to hook something non-supported by an `HookMixin` subclass. Shouldn't ever happen at runtime, but will make programming errors more visible. I accidentally broke the search module `Wiki` hooks when moving stuff to `WikiPage`, and thought this would be helpful to make that sort of thing more noticable.

Cause an error when trying to hook invalid HookMixin method

---

realms/modules/auth/oauth/models.py

Github has an option to keep your email address private. When an user logs in via github oauth, currently all of their edits will have anon@anon.anon email. When viewing the wiki repo history in github this all gets interpreted as one user. This commit sets the email for github users with private email addresses to `<username>@users.noreply.github.com`, which github recognizes as belonging to the proper user.
Instead of making conditionals in the class, I just added the ability for the field maps to contain lambda functions.

Use github's anonymous email when github auth user has private email

---

README.md
realms/__init__.py
realms/config/__init__.py
realms/modules/auth/__init__.py
realms/modules/auth/models.py
realms/modules/auth/proxy/__init__.py
realms/modules/auth/proxy/hooks.py
realms/modules/auth/proxy/models.py
realms/modules/auth/views.py
realms/modules/search/views.py
realms/modules/wiki/views.py
realms/templates/layout.html

Hello,
a simple modification to delegate authentication to the upstream reverse proxy.
When in config `AUTH_PROXY = True`, Realms will look in the HTTP request for header `REMOTE_USER` (classically used by HTTP servers and SSO). If `REMOTE_USER` is given, the user is automatically logged in Realms.
I added a bit of documentation in README too.
Please review.
Thanks,
Stephane
(and I lost 30 minutes to understand that in flask 0.11 is_authenticated is now a property ;))

Authentication by proxy

---

MANIFEST.in

Hello,
install via pip seems broken.
```
virtualenv testrealms
source testrealms/bin/activate
pip install realms-wiki
realms-wiki dev
```
... gives in browser the exception: `TemplateNotFound: wiki/page.html"`
Looks like MANIFEST.in is missing paths to templates insides modules...

add templates from modules to MANIFEST.in

---

MANIFEST.in

Static files in modules were not being selected by MANIFEST.in, this fixes that. It also greatly simplifies the manifest file, and includes all modules static and template files without having to explicitly add new ones. One change is that it will now include all files in the static directory, instead of just the individual css, js, vendor subdirs. Is that an issue? I'm thinking nothing should be put in the static folder that isn't meant to be a part of the dist.

Make sure module static files are included in distributions

---

realms/config/__init__.py

This makes ALLOW_ANON config setting a property, such that it can be overridden by PRIVATE_WIKI. Fixes #182 , and might make config error cases like #138 better.

Don't ALLOW_ANON on a PRIVATE_WIKI. fix #182

---

README.md
realms/__init__.py

This updates the list of .deb packages so it works with Ubuntu 16.04.
It also gives an example systemd init script. (Ubuntu switched from Upstart to Systemd in release 15.04.)
(Please note, this does not constitute an endorsement of systemd.)

Systemd docs

---

README.md
realms/__init__.py

To me, the primary benefit of a git-and-file-based wiki is that one can also use plain git + text editor to maintain the wiki (in addition to using the beautiful browser interface).
Realms is currently incompatible with this type of usage, because it keeps its cached pages forever (unless the user makes a change using the Realms GUI). It will ignore a new git commit that was not made via the Realms GUI, because it finds its old cached HTML and thinks that old HTML is still valid.
This commit adds a 5 second cache timeout, thus causing offline git commits to show up no later than 5s later (when the Realms cache expires). The hard-coded magic number of 5s will limit the number of cache refreshes to 12 per second, which still provides good caching for busy servers, but now allows us SSH+vi …

Add cache timeout of 5s, now works with offline git commits

---

README.md
realms/modules/auth/oauth/views.py

Adding google oauth domain restriction
* You can restrict domain if using google oauth
* README has example
```
"OAUTH": {
"google": {
"key": "",
"secret": "",
"domain": ""    # this is optional if you want to restrict to a GSuite domain
}
```

[Feature] Adding google oauth domain restriction

---

realms/__init__.py
realms/modules/wiki/static/js/editor.js

This is a thorny issue and I do not fully understand how this is supposed to work on the wsgi/flask level.
What I do know is this: on WSGI, we need to know our `RELATIVE_PATH` for edit/delete (which are form submissions), but our blueprints need to be relative to /, because WSGI does the translation for us.
This patch should at least have minimal impact.

Fix relative paths on WSGI.

---

.gitignore
docker-compose.yml
docker/Dockerfile

The Dockerfile has been fixed. Builds an image that runs fine in docker. An accompanying docker-compose.yml file is also provided for ease. Create an empty folder 'realms-data' after clone to hold the wiki data external to the docker container.

Fixed Dockerfile, added docker-compose.yml
